### ISSUE TITLE
Alternative Evaluation

### ISSUE THREAD

**Issue by rlwPosits** [pekkalacd/NetworkProject#5]
We might want to look into validating user input to ensure it's an expression or implement simple math functions to process the input instead of using eval()

**Comment by achaturvedi31** [comment]
import re

math_calc = input("Please enter a basic math calculation as a string: ")
if not re.match("^[0-9\+\-\*\/\ \(\)]*$", math_calc):
    print ("Error! Invalid input")
else:
    print("Your basic math calculation is "+ math_calc)

**Comment by pekkalacd** [comment]
see the pull request, i added EquationSolver class for this, that was sent earlier in the chat. if yall want to use that.

**Comment by rlwPosits** [comment]
going with equation solver to resolve equation validation
